### PR TITLE
1192556 - The way to dig out apipie-binding auth changed in 0.11

### PR DESCRIPTION
**Pull request by ggainey**
Underlying libraries changed in incompatible ways - adapt or die!

### CODE REVIEW

**Comment by mbacovsky** [comment]
Depending on instance variables is error prone, as they are not part of the library interface and can change even between minor versions. 

If I understand it correctly the credentials obtained in the code above are used only for calling `repository upload-content` command from import. I'd suggest to reuse existing connection which will also prevent issues when we e.g. introduce other auth methods to hammer.

I'd suggest to call the `upload-content` command as follows:

```ruby
        require('hammer_cli_katello/repository')
        HammerCLIKatello::Repository::UploadContentCommand.new("", context).run({'id' => <id>, 'path' => <path>})
```
@ggainey, does it make sense?

**Comment by ggainey** [comment]
Aye, belike - will experiment to make sure I don't inadvertently break something. I've never been happy with digging out the auth-info, this feels like it solves the problem better.

**Comment by ggainey** [comment]
@mbacovsky  - yes, makes sense - but still not quite there.

Changing configfile.rb like this:
```ruby
require('hammer_cli_katello/repository')
debug "rc = HammerCLIKatello::Repository::UploadContentCommand.new(\"\", context).run({'id' => #{repo['id']}, 'path' => #{built_module_p
rc = HammerCLIKatello::Repository::UploadContentCommand.new("", context).run({'id' => repo['id'], 'path' => built_module_path})
puts ">>> UPLOAD RC = #{rc.inspect}"
```
results in the following:
```
rc = HammerCLIKatello::Repository::UploadContentCommand.new("", context).run({'id' => 1, 'path' => /root/puppet_work_dir/redhatsatelliteengineering-test_channel/pkg/redhatsatelliteengineering-test_channel-1.0.0.tar.gz})
Could not upload the content:
  Error: option '--path' is required
  
  See: ' --help'
>>> UPLOAD RC = 64
```
What am I missing?

**Comment by ggainey** [comment]
nm, got it - run wants an array, not a hash:

```ruby
.run(%W(--id #{repo['id']} --path #{built_module_path}))
```

**Comment by mbacovsky** [comment]
@ggainey, ahh yes you are right. So does it mean it works now?

**Pull request merged**
